---
title: "Testing computeTE"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Installing compute_TE via R

Run the code cell below to install Transfer Entropy package used by McMullin
```{r setup}
# Needed to install repos from github
install.packages("remotes")
require("remotes")
install_github("Healthcast/TransEnt")
```

## import Transfer Entropy package 
```{r import TE}
require("TransferEntropy")
```

## Running TE example to make sure package installed well.

The code below computes transfer entropy using 1 neighbor with a look back of 3
```{r test}
## Intitialize two vectors of length 10001
X <- rep(0,10000+1)
Y <- rep(0,10000+1)
## Create two linked random processes. Y is independent of X,
## while X is determined in part by the previous values of Y.
for(i in 1:10000){
 Y[i+1] <- 0.6*Y[i] + rnorm(1)
 X[i+1] <- 0.4*X[i] + 0.6*Y[i] + rnorm(1)
}
X <- X[101:10000]
Y <- Y[101:10000]
## Compute the TE from Y to X
computeTE(X,Y,3,1,"MI_diff")  ## should be circa 0.16

```

## Reading in data and running computeTE
```{r compute TE}
df <- read.csv2("/Users/jarvis/GoogleDrive/Playground/PhDStuff/TransferEntropy/testData/df_100_nodup.csv", sep = ",",
                header=T)

# Note: The columns should not be factors otherwise computeTE will crash R
X1 <- as.numeric(df$security.price)
X2 <- as.numeric(df$option.price)

#computeTE(df$security.price, df$option.price, 1, 1, method = "MI_diff")
computeTE(X1, X2, 1, 1, method = "MI_diff")

```


